{% set version = "2.6.11" %}
{% set version_list = version.split('.') %}
{% set tarversion = version_list[0]+version_list[1]+'r'+version_list[2] %}
{% set name = "nauty" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://pallini.di.uniroma1.it/nauty{{ tarversion }}.tar.gz  # [not win]
  sha256: 5ed401917f641af6bf7617a18561b8f1ff5d6563268d815a054786c1ceace617  # [not win]
  url: https://github.com/conda-forge/nauty-feedstock/files/3713871/nauty26r11.tar.gz  # [win]
  sha256: d916e1a932d8e3cdee0e6bd3d3157d8c7ed859a0c62c9bb70c567bdef1e76443   # [win]
  patches:
    - minmax.patch
    - ar.patch

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - make                  # [unix]
    - clangdev              # [win]
    - llvmdev               # [win]
    - lld                   # [win]
    - m2-make               # [win]
    - m2-automake-wrapper   # [win]
    - m2-libtool            # [win]
    - m2-autoconf           # [win]
    - posix                 # [win]

test:
  commands:
    - addedgeg -help
    - test -f $PREFIX/include/nauty/nauty.h                 # [unix]
    - if not exist %LIBRARY_INC%/nauty/nauty.h exit 1       # [win]
    - test -f $PREFIX/lib/libnauty.a                        # [unix]
    - if not exist %LIBRARY_LIB%/nauty.lib exit 1           # [win]

about:
  home: http://users.cecs.anu.edu.au/~bdm/nauty/
  license: Apache-2.0
  license_file: COPYRIGHT
  summary: nauty and Traces are programs for computing automorphism groups of graphs and digraphs.

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
