{% set version = "2.6.7" %}
{% set version_list = version.split('.') %}
{% set tarversion = version_list[0]+version_list[1]+'r'+version_list[2] %}
{% set name = "nauty" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ tarversion }}.tar.gz
  url: http://users.cecs.anu.edu.au/~bdm/nauty/nauty{{ tarversion }}.tar.gz   # [not win]
  sha256: 97b5648de17645895cbd56a9a0b3e23cf01f5332c476d013ea459f1a0363cdc6    # [not win]
  patches:              # [not win]
    - minmax.patch      # [not win]
    - ar.patch          # [not win]

build:
  number: 1001
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev              # [win]
    - lld                   # [win]
    - m2-make               # [win]
    - m2-automake-wrapper   # [win]
    - m2-libtool            # [win]
    - m2-autoconf           # [win]
    - curl                  # [win]
    - m2-patch              # [win]
    - m2-tar                # [win]
    - posix                 # [win]
  host:

test:
  commands:
    - addedgeg -help
    - test -f $PREFIX/include/nauty/nauty.h                 # [unix]
    - if not exist %LIBRARY_INC%/nauty/nauty.h exit 1       # [win]
    - test -f $PREFIX/lib/libnauty.a                        # [unix]
    - if not exist %LIBRARY_LIB%/nauty.lib exit 1           # [win]

about:
  home: http://users.cecs.anu.edu.au/~bdm/nauty/
  license: other
  license_file: COPYRIGHT
  summary: nauty and Traces are programs for computing automorphism groups of graphs and digraphs.

extra:
  recipe-maintainers:
    - isuruf
