travis:
  secure:
    BINSTAR_TOKEN: eJxzVw7SUfLgUo+JCpQNFBJwVFGT8r3gQk1asmbyCAnWsLj8HdNM+AYEFFEeBJGw64hrjLdgn7QStEC+XB4ruN1fmZtAHGGEdF2fKIowZK1cohhRiM05UmUxk92qE8qWgQQTp1URyV21hbigACJSSpvbmeRVfs7G0N8GBQhISIiWPpZeBQNg7dcvF5AbXDWQVR2JrccuZAAPRiZASviDUp/J5Frg89GqtGCSA1gP7YcTmbpFyQuxJq4yvGFQnQ6h3g6C5H4URY9k6J+sQG3pzBfHL2RuuQ5iFMzO80za9oO+TdaqCjdUBzCvcdJvcQkPfcWDv5yVDdJdb551wYuK5KTTZocO0PbwJLRdhOXaabsh9etouyGkzInnD0M4sN27vha47gXep22bEDyggWvlsiCRNp5wed0OYfvVNUaDxDolX0RAmUrMHJ66iXRcGg0mMJ34LwUb/cos2SESFLAOM2kBEZwCdf7ytw+lInPIAWtXmFEQziYaKbuAfhbiRfApgJE2XFHFswj7LKRpRuxKCu0xS5FsKknHeDS669Z6lIYDPE3g2sE6osGzER1fHPvY4crBjjUHTcoeUcgc41xP9YAtbcGtLAYm6II37Gedqyd+Y942A85rk+yHwNafnInnIusURbyVhucLolupM8ZMsm8p/m0r8DLBlAzwzrF7kSc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
