travis:
  secure:
    BINSTAR_TOKEN: mlPfgVrm9HF9PdFd98nDbgaPmasnPvCEWZq/8O5CVtz8VWsZHUcRaO1BEAvQLpXydhIGDmYhYAic51ZoPTBIZcgsAqyAV3Em12tlb2D6jJ5MHcsvEmv8uHpQBY283A4r9rY7IZf9lzhzjRDnXWXjkPKTIgVnZYMqz6N4UzdujESEP59Rej7jxnDF0qLGRrHJJJpnmnpOF5dG6DmV1SSih7qNYotDsmKbCD0ppKtB4K2vPm4OCPDcudbk8sKTcGjIhRZ99zwMWLBNEEAYv877m0D5UhPBRkIIfEtbi96pObxgTunPWlwy2TABu8god+AKPOErBCwW+Y/5fgJpfGB9KLkVq4YKhy36r14mGJhPsC2DX0wRF29vI4qNlJOuQgNWWhqQdcbKwZ0qyEGHTn+5DOa1iS0o2mj03ER56eagmoa0ZJhmvh4i3+e0Mmdz/6m7GMo0jgXMlCpP2ZTuyr9226+uZ19r8shMoyZjQ0I2mxUBqk4RR5Uv/cjW5g4MHMQFXQ9VL3sLIlzX+K5GNT3mbFb7NlAZu0jHVtCZqNu04FF/sk+Bvw9WkcUVxqYcVNgxU+FZhVMLgH4/94S3gyVnlrbnoK123FaONWjevv3NiXL1XrNz55+t5P9a1mq7+TaIAZPCO0sZgU2vtCGwNZTHm5vg+RmJ/NVb54fZYPml4mk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
